export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const SEARCH_NEARBY = "SEARCH_NEARBY";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";

//BROWSE ACTIONS
export const SEARCH_ALL = "SEARCH_ALL";

//USER ACTIONS
export const FETCH_USERS_EVENTS = "FETCH_USERS_EVENTS";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_SIGNOUT = "USER_SIGNOUT";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED";

//EVENTS ACTIONS
export const LOADING_EVENTS = "LOADING_EVENTS";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_NEARBY_EVENTS_SUCCESS = "FETCH_NEARBY_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";
export const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS";
export const POST_EVENT_ERROR = "POST_EVENT_ERROR";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const LOADING_PARTICIPANTS = "LOADING_PARTICIPANTS";
export const GET_PARTICIPANTS_SUCCESS = "GET_PARTICIPANTS_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const UNREGISTER_SUCCESS = "UNREGISTER_SUCCESS";

//LOCATION ACTIONS
export const GET_LOCATIONS = "GET_LOCATION";
export const GET_LOCATIONS_LOADING = "GET_LOCATION_LOADING";
export const GET_LOCATIONS_ERROR = "GET_LOCATION_ERROR";
export const SEARCH_LOCATIONS_RESULT = "SEARCH_LOCATIONS_RESULT";
export const GET_CURRENT_LOCATION_SUCCESS = "GET_CURRENT_LOCATION_SUCCESS";
export const GET_CURRENT_LOCATION_ERROR = "GET_CURRENT_LOCATION_ERROR";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
