//HOME ACTIONS
import firebase from "../Firebase";

export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const SEARCH_NEARBY = "SEARCH_NEARBY";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";

//BROWSE ACTIONS
export const SEARCH_ALL = "SEARCH_ALL";

//USER ACTIONS
export const FETCH_USERS_EVENTS = "FETCH_USERS_EVENTS";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";


//EVENTS ACTIONS
export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
