//HOME ACTIONS
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const SEARCH_NEARBY = "SEARCH_NEARBY";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";

//BROWSE ACTIONS
export const SEARCH_ALL = "SEARCH_ALL";

//USER ACTIONS
export const FETCH_USERS_EVENTS = "FETCH_USERS_EVENTS";

//EVENTS ACTIONS
export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
