//HOME ACTIONS
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const SEARCH_NEARBY = "SEARCH_NEARBY";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";

//BROWSE ACTIONS
export const SEARCH_ALL = "SEARCH_ALL";

//USER ACTIONS
export const FETCH_USERS_EVENTS = "FETCH_USERS_EVENTS";

//EVENTS ACTIONS
export const LOADING_EVENTS = "LOADING_EVENTS";
export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
export const FETCH_NEARBY_EVENTS_SUCCESS = "FETCH_NEARBY_EVENTS_SUCCESS";
export const FETCH_NEARBY_EVENTS_ERROR = "FETCH_NEARBY_EVENTS_ERROR";

//LOCATION ACTIONS
export const GET_LOCATIONS = "GET_LOCATION";
export const GET_LOCATIONS_LOADING = "GET_LOCATION_LOADING";
export const GET_LOCATIONS_ERROR = "GET_LOCATION_ERROR";
export const SEARCH_LOCATIONS_RESULT = "SEARCH_LOCATIONS_RESULT";
